build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix,5@x86_64@seh@posix,6@x86_64@seh@posix,7@x86_64@seh@posix"

install:
  - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
